### ISSUE TITLE
Make the TTN server configurable

### ISSUE THREAD

**Issue by marcelstoer** [netceteragroup/rpi-ttn-gateway#7]
Currently we're setting the EU server statically at https://github.com/netceteragroup/rpi-ttn-gateway/blob/master/Dockerfile#L35.

We should allow users to pick a _region_ (not the actual hostname) based on their country as per:

```
router.eu.thethings.network # EU 433 and EU 863-870
router.us.thethings.network # US 902-928
router.cn.thethings.network # China 470-510 and 779-787
router.au.thethings.network # Australia 915-928 MHz
```

Reference: https://www.thethingsnetwork.org/forum/t/new-addresses-for-cloud-services-update-your-gateways/1813

**Comment by squix78** [comment]
We might consider going even further. We have showed in an experimental setup that gateways can be configured to serve different networks, e.g. Loriot and TTN at the same time. But I guess this requirement should not be solved through environment variables but by providing the config file
